plugins/Users/config/routes.php
<?php
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

Router::plugin(
    'Users',
    ['path' => '/users'],
    function (RouteBuilder $routes) {
        $routes->fallbacks('DashedRoute');
    }
);

plugins/Users/src/Model/Entity/User.php
<?php
namespace Users\Model\Entity;

use Cake\Auth\DefaultPasswordHasher;
use Cake\ORM\Entity;

/**
 * User Entity
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property bool $role
 * @property \Cake\I18n\Time $created
 * @property string $token_password
 * @property int $status
 * @property int $user_info_id
 *
 * @property \Users\Model\Entity\UserInfo $user_info
 */
class User extends Entity{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    protected function _setPassword($value){
        $hasher = new DefaultPasswordHasher();
        return $hasher->hash($value);
    }
    
    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];
}

plugins/Users/src/Model/Entity/Userinfo.php
<?php
namespace Users\Model\Entity;

use Cake\ORM\Entity;

/**
 * UserInfo Entity
 *
 * @property int $id
 * @property string $rut
 * @property string $name
 * @property string $lastname
 * @property string $address
 * @property string $tel_phone
 * @property string $tel_cellphone
 *
 * @property \Users\Model\Entity\User[] $users
 */
class Userinfo extends Entity{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
    
    protected function _getFullName(){
        return $this->_properties['name'] . '  ' .$this->_properties['lastname'];
    }
}

plugins/Users/src/Model/Table/UsersTable.php
<?php
namespace Users\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Users Model
 *
 * @property \Cake\ORM\Association\BelongsTo $UserInfos
 *
 * @method \Users\Model\Entity\User get($primaryKey, $options = [])
 * @method \Users\Model\Entity\User newEntity($data = null, array $options = [])
 * @method \Users\Model\Entity\User[] newEntities(array $data, array $options = [])
 * @method \Users\Model\Entity\User|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \Users\Model\Entity\User patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \Users\Model\Entity\User[] patchEntities($entities, array $data, array $options = [])
 * @method \Users\Model\Entity\User findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class UsersTable extends Table{
    
    public $_roles = [
        0 => 'Administrador',
        1 => 'Usuario'
    ];
    
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config){
        parent::initialize($config);

        $this->table('users');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->addBehavior('Log',[
            'plugin' => 'Users',
            'useTable' => 'UserLogs',
            'messageCreate' => __('Se ha creado un nuevo usuario.'),
            'messageUpdate' => __('Se ha modificado un usuario.'),
            'messageDelete' => __('Se ha eliminado un usuario')
        ]);
        $this->belongsTo('Userinfos', [
            'foreignKey' => 'userinfo_id',
            'className' => 'Users.Userinfos'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator){
        
        $validator
            ->requirePresence('username', 'true')
            ->notEmpty('username','Debe escribir un nombre de usuario.')
            ->add('username',[
                'unique' => [
                    'rule' => 'validateUnique',
                    'provider' => 'table',
                    'message' => 'Nombre de usuario ya registrado.'
                ]
            ]);

        $validator
            ->requirePresence('password','true')
            ->notEmpty('password','Debe escribir una contraseña.')
            ->add('password', [
                'compare' => [
                    'rule' => ['compareWith', 'confirm_password'],
                    'message' => 'Las contraseñas no coinciden.'
                ]
            ]);

        $validator
            ->requirePresence('email', 'true')
            ->notEmpty('email','Debe escribir su correo electrónico.')
            ->add('email',[
                'valid-email' => [
                    'rule' => 'email',
                    'message' => 'Formato de email inválido.'
                ],
                'unique' => [
                    'rule' => 'validateUnique',
                    'provider' => 'table',
                    'message' => 'Email ya registrado.'
                ]
            ]);

        $validator
            ->requirePresence('role', 'true')
            ->notEmpty('role', 'Debe escoger un rol de usuario');

        $validator
            ->allowEmpty('token_password');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules){
        $rules->add($rules->isUnique(['username']));
        $rules->add($rules->isUnique(['email']));

        return $rules;
    }
    
    public function validationUpdatePassword(Validator $validator ){
        $validator
            ->add('password', [
                'length' => [
                    'rule' => ['minLength', 6],
                    'message' => 'La contraseña debe contener por lo menos 6 caracteres.',
                ],
                'match' => [
                    'rule' => ['compareWith','confirm_password'],
                    'message' => 'Las contraseñas no coinciden.',
                ]
            ])
            ->notEmpty('password');
 
        return $validator;
    }
}

plugins/Users/src/Controller/UsersController.php
<?php
namespace Users\Controller;

use Users\Controller\AppController;
use Cake\Mailer\Email;
use Cake\Utility\Hash;

/**
 * Users Controller
 *
 * @property \Users\Model\Table\UsersTable $Users
 */
class UsersController extends AppController{

    public function initialize(){
        parent::initialize();
        $this->loadComponent('Paginator');
        $this->Auth->allow([
            'admin_requestNewPassword',
            'admin_changePassword',
            'admin_add'
        ]);
    }
    
    /**
     * Login method
     *
     * @return \Cake\Network\Response|null
     */
    public function admin_login(){
        if ($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error('Nombre de usuario o contraseña incorrectos.');
        }
    }
    
    /**
     * Logout method
     *
     * @return \Cake\Network\Response|null Redirects to index.
     */
    public function admin_logout(){
        $this->Flash->success('Te haz desconectado.');
        return $this->redirect($this->Auth->logout());
    }
    
    public function register(){
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            if ($this->Users->save($user)) {
                $this->Flash->success(__('El usuario ha sido guardado.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
            }
        }
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }
    
    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function admin_index(){
        $this->paginate = [
            'contain' => ['Userinfos']
        ];
        $users = $this->paginate($this->Users);

        $this->set('roles', $this->Users->_roles);
        $this->set(compact('users'));
        $this->set('_serialize', ['users']);
    }
    
    /**
     * admin_dashboard method
     * Mostramos el dashboard del usuario administrador, con los logs correspondientes.
     *
     * @return \Cake\Network\Response|null
     */
    public function admin_dashboard(){
        $logsTable = parent::getTableInstance('Logs');
        $userLogsTable = parent::getTableInstance('Users.UserLogs');
        
        if($this->request->is('post')){
            if(empty($this->request->data['actions'])){
                $this->Flash->error(__('Escoja una opción válida.'));
            } else{
                # Si seleccionó marcar como leídos (seleccionados) o eliminar (seleccionados)
                if(isset($this->request->data['chk']) && in_array($this->request->data['actions'],[1,3])){
                    $selected = Hash::extract($this->request->data['chk'],'{n}.id');
                    if(empty($selected)){
                        $this->Flash->error(__('Debe escojer por lo menos un registro.'));
                    } else {
                        if($this->request->data['actions'] == 1){
                            $query = $userLogsTable->find('all',[
                                'conditions' => ['UserLogs.id IN' => $selected]
                            ])->toArray();
                            foreach($query as $row){
                                $row->status = 1;
                                $userLogsTable->save($row);
                            }
                            $this->Flash->success(__('Registros guardados como leídos.'));
                        }else{
                            $userLogsTable->deleteAll(['id' => $selected]);
                        }
                    }
                } else {
                    
                }
            }
        }
        
        
        
        
        $logs = $logsTable->find('all');
        
        
        
        $cantNewUsers = $userLogsTable->find('all',['conditions' => ['action' => 'create']])->count();
        
        $users = $this->Users->find('list',[
            'keyField' => 'id',
            'valueField' => 'username'
        ])->toArray();
        
        $this->set(compact('logs','cantNewUsers','users'));
        $this->set('_serialize', ['logs','userLogs']);
    }

    /**
     * View method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null){
        $user = $this->Users->get($id, [
            'contain' => []
        ]);

        $this->set('user', $user);
        $this->set('_serialize', ['user']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function admin_add(){
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->data,[
                'associated' => [
                    'Userinfos'
                ]
            ]);
            if($this->Users->hasBehavior('Log')){
                $this->Users->setUserToLog($this->Auth->user('id'));
            }
            if ($this->Users->save($user)) {
                $this->Flash->success(__('El usuario ha sido guardado.'));
                return $this->redirect(['action' => 'index', 'admin' => true]);
            } else {
                $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
            }
        }
        $this->set('roles',$this->Users->_roles);
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Edit method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function admin_edit($id = null){
        $user = $this->Users->get($id, [
            'contain' => ['Userinfos']
        ]);
        unset($user->password);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->data);
            if($this->Users->hasBehavior('Log')){
                $this->Users->setUserToLog($this->Auth->user('id'));
            }
            if ($this->Users->save($user)) {
                $this->Flash->success(__('El usuario ha sido guardado.'));

                return $this->redirect(['action' => 'index', 'admin' => true]);
            } else {
                $this->Flash->error(__('El usuario no pudo ser guardado. Por favor, intente nuevamente.'));
                unset($user->password);
                unset($user->confirm_password);
            }
        }
        $this->set('roles',$this->Users->_roles);
        $this->set(compact('user'));
        $this->set('_serialize', ['user']);
    }

    /**
     * Delete method
     *
     * @param string|null $id User id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function admin_delete($id = null){
        $this->request->allowMethod(['post', 'delete']);
        $user = $this->Users->get($id);
        if($this->Users->hasBehavior('Log')){
            $this->Users->setUserToLog($this->Auth->user('id'));
        }
        if ($this->Users->delete($user)) {
            $this->Flash->success(__('El usuario ha sido eliminado.'));
        } else {
            $this->Flash->error(__('El usuario no pudo ser eliminado. Por favor, intente nuevamente.'));
        }

        return $this->redirect(['action' => 'index', 'admin' => true]);
    }
    
    /**
     * admin_changeStatus
     *
     * @param int $id User id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function admin_changeStatus($id = null){
        $user = $this->Users->get($id);
        $user->status = $user->status ? 0 : 1;
        $this->Users->save($user);
        $this->Flash->success(__('Usuario actualizado.'));
        return $this->redirect(['action' => 'index', 'admin' => true]);
    }
    
    /**
     * admin_requestNewPassword function
     *
     * Busca si existe el mail ingresado para enviarle un correo con el link para renovar la contraseña
     *
     * @return void
     */
    public function admin_requestNewPassword(){
        if($this->request->is('post')){
            $query = $this->Users->find('all',[
                'conditions' => [
                    'Users.email' => $this->request->data['email']
                ]
            ])->first();
            if(empty($query)){
                $this->Flash->error('El correo electrónico no está registrado.');
            } else {
                $this->sendRequestPasswordEmail($query);
            }
        }
    }
    
    /** Custom Functions **/
    
    /**
     * admin_changePassword
     *
     * @param string $token
     * @return a redirect to admin_login
     */
    public function admin_changePassword($token){
        $user = $this->Users->findByToken($token)->first();
        unset($user->password);
        
        # validamos que el token exista
        if(empty($user)){
            $this->Flash->error(__('Token inválido.'));
            return $this->redirect(['action' => 'login', 'admin' => true]);
        
        # validamos que el token no haya expirado (tiene una duración de 10 minutos)

plugins/Users/src/Template/Users/admin_change_password.ctp
<div class="login-box-body">
    <?= $this->Flash->render();?>
    <p class="login-box-msg"><?=__('Cambiar contraseña.');?></p>
    <?php
        echo $this->Form->create($user,[
            'novalidate' => true,
            'templates' => [
                'inputContainer' => '
                <div class="form-group has-feedback {{errorClass}}">
                    {{content}}
                    <span class="glyphicon {{icoClass}} form-control-feedback"></span>
                    {{errorMessage}}
                </div>'
            ]
        ]);
        
        echo $this->Form->input('password',[
                'placeholder' => __('Nueva Contraseña'),
                'label' => false,
                'class' => 'form-control',
                'div' => false,
                'templateVars' => [
                    'icoClass' => 'glyphicon-lock',
                    'errorClass' => ($this->Form->isFieldError('password') ? 'has-error' : ''),
                    'errorMessage' => $this->Form->error('password')
                ],
                'error' => false
        ]);
        
        echo $this->Form->input('confirm_password',[
                'placeholder' => __('Confirmar Contraseña'),
                'label' => false,
                'div' => false,
                'type' => 'password',
                'class' => 'form-control',
                'templateVars' => [
                    'icoClass' => 'glyphicon-lock'
                ],
                'error' => false
        ]);
    ?>
        <div class="row">
            <div class="col-xs-12">
                <?=$this->Form->submit('Guardar',[
                        'class' => 'btn btn-primary btn-block btn-flat pull-right',
                        'style' => 'width:40%;',
                        'div' => false
                ]);?>
            </div>
        </div>
    <?=$this->Form->end();?>
</div>

plugins/Users/src/Template/Users/admin_dashboard.ctp
<?php $this->assign('title', 'FIE | Dashboard'); ?>
<?php echo $this->Html->script('Users.admin_get_log_list'); ?>
<section class="content-header">
    <h1>Dashboard</h1>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i>
            <?=$this->Html->link('Home',['action' => 'dashboard', 'admin' => true],['title' => 'Ir a','escape' => false]);?>
        </li>
        <li class="active">
            Dashboard
        </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3><?=$cantNewUsers;?></h3>
                    <p><?=__('Nuevos usuarios');?></p>
                </div>
                <div class="icon"><i class="ion ion-person-add"></i></div>
                <?=$this->Html->link('Más información <i class="fa fa-arrow-circle-right"></i>','',['class' => 'small-box-footer', 'escape' => false]);?>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>22</h3>
                    <p><?=__('Nuevas postulaciones');?></p>
                </div>
                <div class="icon"><i class="ion ion-ios-paper"></i></div>
                <?=$this->Html->link('Más información <i class="fa fa-arrow-circle-right"></i>','',['class' => 'small-box-footer', 'escape' => false]);?>
            </div>
        </div>
    </div>
    <div class="box box-primary">
        <div class="box-header">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title"><?=__('Registros de Usuarios');?></h3>
        </div>
        <?=$this->Form->create('Filter',['novalidate' => true, 'id' => 'AdminDashboardForm']);?>
        <div class="box-body">
            <?=$this->Flash->render();?>
                <div class="form-group col-lg-4">
                    <label><?=__('Mostrar:');?></label>
                    <?=$this->Form->select('show',[
                        __('Todos'),
                        __('Sólo creaciones'),
                        __('Sólo modificaciones'),
                        __('Sólo eliminaciones')
                    ],[
                        'class' => 'form-control',
                        'id' => 'AdminDashboardShow'
                    ]);?>
                </div>
                <div class="form-group col-lg-4">
                    <label><?=__('Ordenar:');?></label>
                    <?=$this->Form->select('order',[
                        __('Más recientes primero'),
                        __('Más antiguos primero')
                    ],[
                        'class' => 'form-control',
                        'id' => 'AdminDashboardOrder'
                    ]);?>
                </div>
                <div class="form-group col-lg-4">
                    <label><?=__('Autor:');?></label>
                    <?=$this->Form->select('autor',$users,[
                        'class' => 'form-control',
                        'empty' => 'Seleccione...',
                        'id' => 'AdminDashboardAutor'
                    ]);?>
                </div>
            
            <div class="logs-users-list" style="height: 400px; max-height: 400px;border: 2px solid #E6E7E8; display: flex;"></div>
            <div class="form-group col-lg-3">
                <label><?=__('Acciones para seleccionados:');?></label>
                <?=$this->Form->select('actions',[
                    1 => __('Marcar como leídos (Seleccionados)'),
                    2 => __('Marcar como leídos (Todos)'),
                    3 => __('Eliminar (Seleccionados)'),
                    4 => __('Eliminar (Todos)')
                ],[
                    'empty' => __('Seleccione...'),
                    'class' => 'form-control',
                    'id' => 'AdminDashboardActions'
                ]);?>
            </div>
        </div>
        <?=$this->Form->end();?>
    </div>
</section>

plugins/Users/src/Template/Users/admin_get_log_list.ctp
<style type="text/css">
    .dark-li {
        background: #ECE9E9 none repeat scroll 0 0 !important;
    }
    .todo-list li {
        border-left: none;
    }
</style>
<ul class="todo-list col-lg-1 col-xs-1"><?php
    foreach($userLogs as $key => $log): ?>
        <li style="height: 40px;">
            <?=$this->Form->input('chk.'.$key.'.id',[
                'templates' => [
                    'inputContainer' => '
                        <div class="checkbox" style="margin: 0;">
                            <label>{{content}}</label>
                        </div>'
                ],
                'type' => 'checkbox',
                'value' => $log->id,
                'hiddenField' => false,
                'label' => false
            ]);?>
        </li><?php
    endforeach; ?>
</ul>
<ul class="todo-list col-lg-11 col-xs-11" id="accordion"><?
    foreach($userLogs as $key => $log):
        $totalSeconds = strtotime('now') - strtotime($log->created->format('Y-m-d H:i:s'));
        $hours = floor($totalSeconds/3600);
        
        if($hours == 0){
            $minutes = floor(($totalSeconds/60)%60);
            $text = __('Hace ').$minutes.__(' minutos');
        } elseif($hours > 23) {
            $days = floor($hours/24);
            $text = __('Hace ').$days.__(' días');
        }else{
            $text = __('Hace ').$hours.__(' horas');
        } ?>
        <li style="cursor: pointer;" rel-id="<?=$log->id;?>" data-toggle="modal" data-target="#logInfoModal">
            <div class="li-header">
                <span class="text"><?=$log->message;?></span>
                <small class="label label-info"><i class="fa fa-clock-o"></i> <?=$text;?></small>
            </div>
        </li><?
    endforeach; ?>
</ul>
<div class="modal fade" id="logInfoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        $('#accordion li').on('click',function(){
            $.ajax({
                url: '/admin/dashboard/mostrar-log/'+$(this).attr('rel-id'),
                success: function(data){
                    $('.modal-content').html(data);
                }
            });
        });
        $('#accordion li').hover(function(){
            var assoc = $(this).attr('rel-id');
            if($(this).hasClass('dark-li')){
                $(this).removeClass('dark-li');
                $('#chk-'+assoc).parent().parent().parent().removeClass('dark-li');
            }else{
                $(this).addClass('dark-li');
                $('#chk-'+assoc).parent().parent().parent().addClass('dark-li');
            }
        });
        $('.checkbox').hover(function(){
            var assoc = $(this).find('input[type="checkbox"]').val();
            if($(this).parent().hasClass('dark-li')){
                $(this).parent().removeClass('dark-li');
                $('#accordion li[rel-id="'+assoc+'"]').removeClass('dark-li');
            }else{
                $(this).parent().addClass('dark-li');
                $('#accordion li[rel-id="'+assoc+'"]').addClass('dark-li');
            }
        });
        $('.checkbox').on('click',function(){
            var assoc = $(this).find('input[type="checkbox"]').val();
            if($(this).parent().hasClass('dark-li')){
                $(this).parent().removeClass('dark-li');
                $('#accordion li[rel-id="'+assoc+'"]').removeClass('dark-li');
            }else{
                $(this).parent().addClass('dark-li');
                $('#accordion li[rel-id="'+assoc+'"]').addClass('dark-li');
            }
        });
    });
</script>

plugins/Users/src/Template/Users/admin_index.ctp
<?php $this->assign('title', 'FIE | Listado Usuarios'); ?>
<section class="content-header">
    <h1 class="page-header"><?=__('Usuarios');?></h2>
    <ol class="breadcrumb">
        <li>
            <i class="fa fa-dashboard"></i>
            <?=$this->Html->link(__('Dashboard'),['action' => 'dashboard', 'admin' => true]);?>
        </li>
        <li class="active">
            <i class="fa fa-users"></i> <?=__('Usuarios');?>
        </li>
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <?=$this->Flash->render();?>
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"><?=__('Listado Usuarios Registrados');?></h3>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <style type="text/css">
                                thead th { color: #3c8dbc; }
                            </style>
                            <table class="table table-bordered table-hover dataTable">
                                <thead>
                                    <th><?= __('#') ?></th>
                                    <th><?= __('Rut') ?></th>
                                    <th><?= __('Username') ?></th>
                                    <th><?= __('Email') ?></th>
                                    <th><?= __('Nombre Completo') ?></th>
                                    <th><?= __('Rol');?></th>
                                    <th><?= __('Estado') ?></th>
                                    <th class="actions text-center"><?= __('Acciones') ?></th>
                                </thead>
                                <tbody>
                                    <?php foreach ($users as $user): ?>
                                    <tr>
                                        <td><?= $this->Number->format($user->id) ?></td>
                                        <td><?= $user->userinfo->rut ?></td>
                                        <td><?= $user->username ?></td>
                                        <td><?= $user->email ?></td>
                                        <td><?= $user->userinfo->full_name ?></td>
                                        <td><?= $roles[$user->role]; ?></td>
                                        <td><?= $user->status == 1 ? 'Habilitado' : 'Deshabilitado' ?></td>
                                        <td class="actions" style="width: 10%;">
                                            <?= $this->Html->link('<i class="fa fa-edit" aria-hidden="true"></i>',
                                                        ['action' => 'edit', 'admin' => true, $user->id],
                                                        ['escape' => false,'title' => 'Editar']);
                                            ?>
                                            <?= $this->Html->link('<i class="fa fa-refresh" aria-hidden="true"></i>',
                                                        ['action' => 'changeStatus', 'admin' => true, $user->id],
                                                        ['escape' => false,'title' => 'Cambiar estado']);
                                            ?>
                                            <?= $this->Form->postLink('<i class="fa fa-trash" aria-hidden="true"></i>',
                                                        ['action' => 'delete', 'admin' => true, $user->id],
                                                        ['escape' => false, 'title' => 'Eliminar',
                                                         'class' => 'pull-right',
                                                         'confirm' => __('¿Estás seguro de querer eliminar al usuario ID # {0}?', $user->id)]);
                                            ?>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 text-center">
                            <ul class="pagination">
                                <?= $this->Paginator->prev('< ' . __('Anterior')) ?>
                                <?= $this->Paginator->numbers() ?>
                                <?= $this->Paginator->next(__('Siguiente') . ' >') ?>
                            </ul>
                            <p><?= $this->Paginator->counter() ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>